"""Add missing columns to task table

NOTE: The task_status enum change for 'testing' is handled in a new migration.

Revision ID: 4f5fa421dbc5
Revises: 774d11bf0701
Create Date: 2025-07-12 13:07:48.010039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5fa421dbc5'
down_revision = '774d11bf0701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('labels', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('team', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('restrict_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linked_work_items', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_task_reporter_id', 'user', ['reporter_id'], ['id'])
        batch_op.create_foreign_key('fk_task_assignee_id', 'user', ['assignee_id'], ['id'])
        batch_op.create_foreign_key('fk_task_parent_id', 'task', ['parent_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('admin', 'user', name='user_roles'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'user', name='user_roles'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_reporter_id', type_='foreignkey')
        batch_op.drop_constraint('fk_task_assignee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_task_parent_id', type_='foreignkey')
        batch_op.drop_column('linked_work_items')
        batch_op.drop_column('restrict_to')
        batch_op.drop_column('flagged')
        batch_op.drop_column('attachment')
        batch_op.drop_column('reporter_id')
        batch_op.drop_column('start_date')
        batch_op.drop_column('team')
        batch_op.drop_column('labels')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('assignee_id')
        batch_op.drop_column('work_type')

    # ### end Alembic commands ###
