"""Add RBAC models and relationships

Revision ID: cc70a80783b7
Revises: 9bdbf1f01fcc
Create Date: 2025-07-20 09:05:01.090544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc70a80783b7'
down_revision = '9bdbf1f01fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_label_name', ['name'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_team_id', 'team', ['team_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_team_leader', sa.Boolean(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('visitor', 'developer', 'team_manager', 'admin', name='user_roles'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_user_team_id', 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_team_id', type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.Enum('visitor', 'developer', 'team_manager', 'admin', name='user_roles'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('is_team_leader')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_team_id', type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_constraint('uq_label_name', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
